---
name: push

on:
  push:
    branches: [main]

jobs:
  default:
    runs-on: ubuntu-latest

    steps:
      - name: Check out source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11

      - name: Release
        run: |
          echo "${{ secrets.MVN_SETTINGS }}" > /root/.m2/settings.xml

          mvn -B release:prepare
          mvn -B release:perform
