---
name: push

on:
  push:
    branches: [main]

jobs:
  default:
    runs-on: ubuntu-latest

    steps:
      - name: Check out source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11

      - name: Release
        uses: qcastel/github-actions-maven-release@master
        with:
          release-branch-name: main
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          git-release-bot-name: "release-bot"
          git-release-bot-email: "release-bot@example.com"  
