---
name: push

on:
  push:
    branches: [main]

jobs:
  default:
    runs-on: ubuntu-latest

    steps:
      - name: Check out source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11

      - name: maven-settings-xml-action
        uses: whelk-io/maven-settings-xml-action@v20
        with:
          servers: '${{ secrets.MAVEN_SERVERS }}'

      - name: Release
        run: |
          git config --global user.email "gareth@bryncynfelin.co.uk"
          git config --global user.name "garethjevans"

          mvn -B release:prepare
          mvn -B release:perform
